name: Brand Theming and Deploy

on:
  workflow_dispatch:
    inputs:
      brand:
        description: 'The brand name to apply'
        required: true
        default: ''
        type: string

env:
  DEFAULT_BRAND: redcow

jobs:
  set-brand-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Clean up asset folders
        run: |
          echo "[INFO] Cleaning up asset folders in src/assets/..."
          find src/assets -mindepth 1 -maxdepth 1 -type d -not -name "${{ github.event.inputs.brand }}" -exec rm -rf {} +
          echo "[SUCCESS] Kept only the '${{ github.event.inputs.brand }}' asset folder."

      - name: Replace brand name in files
        run: |
          echo "[INFO] Replacing brand name in files..."
          grep -rl "${DEFAULT_BRAND}" ./src | xargs sed -i "s/${DEFAULT_BRAND}/${{ github.event.inputs.brand }}/g"
          echo "[SUCCESS] Replaced all instances of '${DEFAULT_BRAND}' with '${{ github.event.inputs.brand }}' in the src directory."

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './dist'
          production-branch: main
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions - Brand: ${{ github.event.inputs.brand }}"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1